import { AgentProfile, Answer, GlossaryTerm, GuideArticle, Question } from "@/lib/types";

export const blockedWords = ["idiot", "bedragare", "lurendrejeri", "svartpengar", "fuskare"];

export const agents: AgentProfile[] = [
  {
    id: "a1",
    fullName: "Anna Lindström",
    slug: "anna-lindstrom-goteborg",
    firm: "MOHV Göteborg City",
    title: "Fastighetsmäklare",
    city: "Göteborg",
    municipalities: ["Göteborg", "Mölndal", "Partille"],
    bio: "Specialiserad på lägenheter i centrala Göteborg och nära tillträdesprocesser för förstagångsköpare.",
    fmiNumber: "FMI-104221",
    verificationStatus: "verified",
    premium: true,
    soldCount: 84,
    activeCount: 12,
    profileViews: 1943,
  },
  {
    id: "a2",
    fullName: "Johan Berg",
    slug: "johan-berg-stockholm",
    firm: "SkandiaMäklarna Vasastan",
    title: "Fastighetsmäklare",
    city: "Stockholm",
    municipalities: ["Stockholm", "Solna", "Sundbyberg"],
    bio: "Driver säljprocesser för bostadsrätter i Stockholm med fokus på maximal slutprisstrategi.",
    fmiNumber: "FMI-337900",
    verificationStatus: "verified",
    premium: false,
    soldCount: 102,
    activeCount: 8,
    profileViews: 2284,
  },
  {
    id: "a3",
    fullName: "Sara Alenius",
    slug: "sara-alenius-malmo",
    firm: "Länsfast Malmö",
    title: "Fastighetsmäklare",
    city: "Malmö",
    municipalities: ["Malmö", "Lund", "Vellinge"],
    bio: "Arbetar med villor och radhus i Skåne, stark på värdering och förhandling.",
    fmiNumber: "FMI-512004",
    verificationStatus: "verified",
    premium: true,
    soldCount: 67,
    activeCount: 15,
    profileViews: 1322,
  },
];

export const questions: Question[] = [
  {
    id: "q1",
    slug: "vad-kostar-det-att-salja-lagenhet-goteborg",
    title: "Vad kostar det att sälja lägenhet i Göteborg?",
    body: "Jag ska eventuellt sälja min 3:a i Linnéstaden. Vilka kostnader bör jag räkna med utöver mäklararvode?",
    askedBy: "Konsument #102",
    audience: "seller",
    category: "salja",
    geoScope: "local",
    municipality: "Göteborg",
    createdAt: "2026-02-10",
    helpfulVotes: 24,
    answerCount: 3,
  },
  {
    id: "q2",
    slug: "hur-fungerar-budgivning-som-kopare",
    title: "Hur fungerar budgivning som köpare?",
    body: "Kan en säljare acceptera ett lägre bud trots att det finns högre bud?",
    askedBy: "Konsument #233",
    audience: "buyer",
    category: "juridik",
    geoScope: "open",
    createdAt: "2026-02-14",
    helpfulVotes: 37,
    answerCount: 2,
  },
  {
    id: "q3",
    slug: "ar-det-lage-att-kopa-bostad-i-malmo-2026",
    title: "Är det läge att köpa bostad i Malmö 2026?",
    body: "Vi planerar att köpa bostadsrätt under våren. Hur ser ni på marknaden just nu?",
    askedBy: "Konsument #418",
    audience: "buyer",
    category: "kopa",
    geoScope: "regional",
    region: "Skåne län",
    createdAt: "2026-02-16",
    helpfulVotes: 19,
    answerCount: 1,
  },
];

export const answers: Answer[] = [
  {
    id: "ans1",
    questionId: "q1",
    answeredBy: "a1",
    body: "Räkna normalt med mäklararvode, styling vid behov, fotograf, eventuell dubbel boendekostnad och mindre fix innan visning. En konkret kalkyl bör tas fram innan signering.",
    helpfulVotes: 13,
    createdAt: "2026-02-11",
    comment: "Om du vill kan jag ge ett exempel på nettoprognos med dagens avgiftsnivåer i Linnéstaden.",
  },
  {
    id: "ans2",
    questionId: "q1",
    answeredBy: "a2",
    body: "Glöm inte latenta kostnader som flytt, magasineringskostnad och eventuell bryggfinansiering om tillträdet inte synkar.",
    helpfulVotes: 6,
    createdAt: "2026-02-11",
  },
  {
    id: "ans3",
    questionId: "q2",
    answeredBy: "a3",
    body: "Ja. Säljaren väljer fritt köpare och pris fram till bindande kontrakt. Högsta bud måste inte vinna, men processen ska vara transparent.",
    helpfulVotes: 22,
    createdAt: "2026-02-15",
  },
];

export const sellerGuides: GuideArticle[] = [
  {
    slug: "salj-bostad-steg-for-steg",
    title: "Sälj bostad steg för steg",
    excerpt: "En praktisk process från första värdering till tillträde.",
    minutes: 8,
    section: "saljare",
    content: [
      "Starta med en realistisk värdering och besluta önskat tidsfönster.",
      "Säkra all dokumentation: föreningens årsredovisning, driftkostnader och eventuella tillägg.",
      "Planera foto, styling och visning med en tydlig budstrategi.",
      "Jämför inte bara arvode utan också leverans: närvaro, kommunikation och avslutsgrad.",
    ],
  },
  {
    slug: "forhandla-maklararvode",
    title: "Förhandla mäklararvode utan att tappa kvalitet",
    excerpt: "Så pressar du kostnad utan att tappa säljkraft.",
    minutes: 6,
    section: "saljare",
    content: [
      "Begär alltid två till tre offerter med samma uppdragsomfattning.",
      "Fråga hur arvodet kopplas till faktisk leverans, inte bara ett procenttal.",
      "Säkra att du får en tydlig plan för spekulantuppföljning efter visning.",
    ],
  },
  {
    slug: "styling-checklista-infor-visning",
    title: "Styling-checklista inför visning",
    excerpt: "Snabba åtgärder som brukar ge stor effekt.",
    minutes: 5,
    section: "saljare",
    content: [
      "Neutralisera ytor och skapa tydliga funktioner i varje rum.",
      "Prioritera ljus, ordning och doftneutralitet.",
      "Lyft fram planlösning och förvaring i bild och visning.",
    ],
  },
  {
    slug: "budgivning-fran-saljarens-perspektiv",
    title: "Budgivning från säljarens perspektiv",
    excerpt: "Hur du fattar rätt beslut när flera bud finns.",
    minutes: 7,
    section: "saljare",
    content: [
      "Bedöm bud utifrån pris, villkor, finansieringsgrad och tillträdesdatum.",
      "Bygg beslut på helhet och inte bara högsta siffran.",
      "Dokumentera allt i budgivningslista för full transparens.",
    ],
  },
  {
    slug: "valj-ratt-maklare",
    title: "Välj rätt mäklare",
    excerpt: "Fem frågor som avslöjar vem som faktiskt levererar.",
    minutes: 4,
    section: "saljare",
    content: [
      "Hur ser din plan ut vecka 1, 2 och 3?",
      "Vilka köpare i ditt register matchar mitt objekt redan idag?",
      "Hur rapporterar du aktivitet mellan visning och budstart?",
    ],
  },
];

export const buyerGuides: GuideArticle[] = [
  {
    slug: "kopa-bostad-steg-for-steg",
    title: "Köpa bostad steg för steg",
    excerpt: "Från första sökning till nyckel i hand.",
    minutes: 9,
    section: "kopare",
    content: [
      "Säkra lånelöftet innan du börjar buda.",
      "Bygg en kravlista som inkluderar avgift, renoveringsbehov och pendling.",
      "Kontrollera föreningens ekonomi och framtida avgiftstryck.",
      "Var tydlig med villkor innan kontrakt signeras.",
    ],
  },
  {
    slug: "rakna-pa-kontantinsats-och-amortering",
    title: "Räkna på kontantinsats och amortering",
    excerpt: "Snabb modell för vad köpet faktiskt kostar varje månad.",
    minutes: 6,
    section: "kopare",
    content: [
      "Kontantinsats är minst 15 procent av köpesumman.",
      "Kombinera bolåneränta, avgift och drift i en total boendekostnad.",
      "Stresstesta kalkylen med högre ränta innan beslut.",
    ],
  },
  {
    slug: "dolda-fel-och-juridiskt-ansvar",
    title: "Dolda fel och juridiskt ansvar",
    excerpt: "Vad du kan kräva och vad du ansvarar för som köpare.",
    minutes: 8,
    section: "kopare",
    content: [
      "Undersökningsplikten är central vid bostadsköp.",
      "Dolda fel kräver att felet inte borde ha upptäckts vid normal kontroll.",
      "Dokumentation och tidslinje är avgörande vid tvist.",
    ],
  },
  {
    slug: "budgivningsstrategi-for-kopare",
    title: "Budgivningsstrategi för köpare",
    excerpt: "Så budar du disciplinerat utan att överbetala.",
    minutes: 5,
    section: "kopare",
    content: [
      "Sätt maxnivå innan budstart och håll den.",
      "Anpassa budtempo efter konkurrens och säljarens tidspress.",
      "Säkra finansiering och tillträdesvillkor tidigt.",
    ],
  },
  {
    slug: "vad-hander-efter-accepterat-bud",
    title: "Vad händer efter accepterat bud?",
    excerpt: "En tydlig tillträdesprocess utan överraskningar.",
    minutes: 7,
    section: "kopare",
    content: [
      "Budaccept är inte bindande innan kontrakt är signerat.",
      "Efter kontrakt följer handpenning, bankkontakt och tillträdesförberedelser.",
      "På tillträdesdagen sker slutbetalning och nyckelöverlämning.",
    ],
  },
];

export const glossaryTerms: GlossaryTerm[] = [
  {
    slug: "lagfart",
    term: "Lagfart",
    definition: "Registrering av vem som är juridisk ägare till en fastighet.",
    whyItMatters: "Kostnaden påverkar din totala kontantinsats och måste planeras i köpkalkylen.",
  },
  {
    slug: "pantbrev",
    term: "Pantbrev",
    definition: "Säkerhet som banken tar i fastigheten för bolån.",
    whyItMatters: "Nya pantbrev innebär extra kostnad vid köp av hus.",
  },
  {
    slug: "kontantinsats",
    term: "Kontantinsats",
    definition: "Den del av köpeskillingen som inte får lånefinansieras.",
    whyItMatters: "Avgör hur dyr bostad du faktiskt kan köpa.",
  },
  {
    slug: "tilltrade",
    term: "Tillträde",
    definition: "Dagen då köparen betalar slutlikvid och får nycklarna.",
    whyItMatters: "Styr flytt, finansiering och ansvarsövergång.",
  },
  {
    slug: "undersokningsplikt",
    term: "Undersökningsplikt",
    definition: "Köparens ansvar att noggrant undersöka objektet innan köp.",
    whyItMatters: "Missade fel kan bli köparens ansvar i efterhand.",
  },
  {
    slug: "dolt-fel",
    term: "Dolt fel",
    definition: "Fel som fanns vid köpet men inte kunde upptäckas trots noggrann undersökning.",
    whyItMatters: "Kan ge rätt till ersättning men kravbilden är hög.",
  },
  {
    slug: "budgivning",
    term: "Budgivning",
    definition: "Process där spekulanter lägger bud på bostaden innan kontrakt.",
    whyItMatters: "Priset och villkoren kan förändras snabbt och kräver strategi.",
  },
  {
    slug: "upplatelseform",
    term: "Upplåtelseform",
    definition: "Hur bostaden ägs juridiskt, till exempel bostadsrätt eller äganderätt.",
    whyItMatters: "Påverkar avgifter, ansvar och finansiering.",
  },
  {
    slug: "driftkostnad",
    term: "Driftkostnad",
    definition: "Löpande kostnader för boendet, exempelvis el, försäkring och uppvärmning.",
    whyItMatters: "Används av banker i kvar-att-leva-på-kalkyler.",
  },
  {
    slug: "forhandsavtal",
    term: "Förhandsavtal",
    definition: "Avtal om framtida köp av nyproducerad bostadsrätt.",
    whyItMatters: "Binder köparen tidigt och kräver kontroll av villkoren.",
  },
];
